version: '3.1'

services:
  redis:
    image: redis
    container_name: conatinerRedis
    ports:
      - 6379:6379
    networks:
      - spring-net

  gongseek:
    image: gongseek
    container_name: gongseek
    build: .
    restart: always
    environment:
      REDIS_HOST: conatinerRedis
      REDOS_PORT: 6379
    ports:
      - 8080:8080
    depends_on:
      - redis
    networks:
      - spring-net

networks:
  spring-net:
