export const URL = {
	HOME: '/',
	LOGIN_CONTROLLER: '/callback',
	REFRESH_TOKEN_HANDLER: '/check-login',
	CATEGORY_SELECTOR: '/category',
	WRITING_ARTICLE: '/article/:category',
	VOTE_GENERATOR: '/votes/:articleId',
	MY_PAGE: '/my-page',
	VOTE_DEADLINE_GENERATOR: '/votes-deadline',
	LOGIN: '/login',
	CATEGORY_ARTICLE: '/articles/:category',
	QUESTION_DETAIL: '/articles/question/:id',
	DISCUSSION_DETAIL: '/articles/discussion/:id',
	MODIFY_ARTICLE: '/articles/modify/:category/:id',
	SEARCH_RESULT: '/search-result',
	HASH_TAG_SEARCH: '/hash-tag',
	INQUIRE: '/inquire',
	NOT_FOUND: '/*',
};
