spring:
  servlet:
    multipart:
      enabled: true
      max-file-size: 28MB
      max-request-size: 128MB

file:
  image-dir: /Users/han-ul/gongseek-image-storage/
  server-path:

server:
  port: 8080
