name: gongseek CI

# 하기 내용에 해당하는 이벤트 발생 시 github action 동작
on:
  pull_request: # 모든 브랜치에서 PR이 일어났을 때 github action 동작
    branches:
      - '*'

jobs:
  test:
      runs-on: ubuntu-22.04 # 실행 환경 지정
      steps:
        - uses: actions/checkout@v2 # github action 버전 지정(major version)

        - name: Set up JDK 11 # JAVA 버전 지정
          uses: actions/setup-java@v1
          with:
            java-version: 11

        - name: Grant execute permission for gradlew
          working-directory: ./backend
          run: chmod +x ./gradlew

        - name: Test with Gradle # test application build
          working-directory: ./backend
          run: ./gradlew test -s
          
  build:
    runs-on: ubuntu-22.04 # 실행 환경 지정
    defaults:
      run:
        working-directory: ./frontend

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "14"

      - name: Install node packages
        run: yarn install

      - name: Test
        run: yarn test

      - name: Build
        run: yarn build
